# Generated by Django 6.0.4 on 2026-07-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('version', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='process', max_length=64)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('curated', models.BooleanField(default=False)),
                ('source_url', models.URLField(max_length=512)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
